name: Publish to https://lmno.lol/crisidev

on:
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Publish blog
        env:
          LMNO_LOL_API_KEY: ${{ secrets.LMNO_LOL_API_KEY }}
        run: |
          ${PWD}/scripts/deploy.sh
